module ItemsHelper

	def BS_convert(name)
		if name == "Accountspayableandaccruedexpenses"
			name = "Accounts Payable and Accrued Expenses"
		elsif name == 'Accruedinterest'
			name = 'Accrued Interest'
		elsif name == 'Additionalpaidincapital'
			name = 'Additional Paid In Capital'
		elsif name == 'Additionalpaidincapitalpreferredstock'
			name = 'Additional Paid In Capital Preferred Stock'
		elsif name == 'Cashandcashequivalents'
			name = 'Cash and Cash Equivalents'
		elsif name == 'Cashcashequivalentsandshortterminvestments'
			name = 'Cash Equivalents and Short Term Investments'
		elsif name == 'Commitmentscontingencies'
			name = 'Commitments and Contingencies'
		elsif name == 'Commonstock'
			name = 'Common Stock'
		elsif name == 'Deferredcharges'
			name = 'Deferred Charges'
		elsif name == 'Deferredincometaxescurrent'
			name = 'Deferred Income Taxes Current'
		elsif name == 'Deferredincometaxeslongterm'
			name = 'Deferred Income Taxes Long term'
		elsif name == 'Intangibleassets'
			name = 'Intangible Assets'
		elsif name == 'Inventoriesnet'
			name = 'Inventories Net'
		elsif name == 'Longtermdeferredincometaxliabilities'
			name = 'Long Term Deferred Income Tax Liabilities'
		elsif name == 'Longtermdeferredliabilitycharges'
			name = 'Long Term Deferred Liability Charges'
		elsif name == 'Longterminvestments'
			name = 'Long Term Investments'
		elsif name == 'Minorityinterest'
			name = 'Minority Interest'
		elsif name == 'Otheraccumulatedcomprehensiveincome'
			name = 'Other Accumulated Comprehensive Income'
		elsif name == 'Otherassets'
			name = 'Other Assets'
		elsif name == 'Othercurrentassets'
			name = 'Other Current Assets'
		elsif name == 'Othercurrentliabilities'
			name = 'Other Current Liabilities'
		elsif name == 'Otherequity'
			name = 'Other Equity'
		elsif name == 'Otherinvestments'
			name = 'Other Investments'
		elsif name == 'Otherliabilities'
			name = 'Other Liabilities'
		elsif name == 'Partnerscapital'
			name = 'Partners Capital'
		elsif name == 'Pensionpostretirementobligation'
			name = 'Pension Post-Retirement Obligation'
		elsif name == 'Preferredstock'
			name = 'Preferred Stock'
		elsif name == 'Prepaidexpenses'
			name = 'Prepaid Expenses'
		elsif name == 'Propertyplantequipmentnet'
			name = 'Property Plant and Equipmentnet'
		elsif name == 'Restrictedcash'
			name = 'Restricted Cash'
		elsif name == 'Retainedearnings'
			name = 'Retained Earnings'
		elsif name == 'Temporaryequity'
			name = 'Temporary Equity'
		elsif name == 'Totalassets'
			name = 'Total Assets'
		elsif name == 'Totalcurrentassets'
			name = 'Total Current Assets'
		elsif name == 'Totalcurrentliabilities'
			name = 'Total Current Liabilities'
		elsif name == 'Totalliabilities'
			name = 'Total Liabilities'
		elsif name == 'Totallongtermdebt'
			name = 'Total Long Term Debt'
		elsif name == 'Totalreceivablesnet'
			name = 'Total Receivables Net'
		elsif name == 'Totalshorttermdebt'
			name = 'Total Short Term Debt'
		elsif name == 'Totalstockholdersequity'
			name = 'Total Stockholders Equity'
		elsif name == 'Treasurystock'
			name = 'Treasury Stock'
		end 
		return name
	end 


	def values_convert(value)
		if value == nil
			value = '-'
		end 

		return value
	end 
end #helper end 
